### ISSUE TITLE
Tinkerit repo might die soon, Google Code service is going to disappear

### ISSUE THREAD

**Issue by timofonic** [xoseperez/weatherstation#1]
Hello.

I made a mirror of the tinkerit site, in order to preserve that information:

https://github.com/timofonic/tinkerit/blob/wiki/SecretThermometer.md
  https://github.com/timofonic/tinkerit/blob/wiki/SecretVoltmeter.md

Maybe you are interested in this project too
https://github.com/svn2github/transistortester

Kind regards.

**Comment by xoseperez** [comment]
I changed the references to the new repo in the README file, thank you!
